### ISSUE TITLE
background image on mobile devices

### ISSUE THREAD

**Issue by jakubjurena** [jakubjurena/DevsOnCoffee-static#1]
# expected output:
google chrome display this in developer tools
![expected](https://user-images.githubusercontent.com/20454882/33241249-21a10964-d2c3-11e7-9ba3-8f42a78dcca1.PNG)

# real output:
real output of mobile device (Xiaomi A1 on Chrome browser)
![real](https://user-images.githubusercontent.com/20454882/33241251-2b436f5c-d2c3-11e7-8fba-0f088abcefff.png)

real output of tablet (Samsung Galaxy Tab A on Chrome browser)
![real_tablet](https://user-images.githubusercontent.com/20454882/33241364-7cc4f0d4-d2c4-11e7-96fd-b7f9694e9cf4.png)

**Comment by TBarborik** [comment]
Easy peasy lemon squezy 🍋 ..
NEVER use absolute position if not really necessary. Hell freezes each time it is used, especially on the body. 
To fix this, remove in https://github.com/jakubjurena/DevsOnCoffee-static/blob/master/css/main.css  first three lines.

![image](https://user-images.githubusercontent.com/2272556/33276062-b86055ea-d394-11e7-827c-b6479c568fa9.png)

**Comment by jakubjurena** [comment]
I deleted absolute position and added `display: table;` in main.css and it is working now.

Thank you Tom
